version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:management-alpine
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_net

    redis:
        image: redis:latest
        container_name: redis
        ports:
        - 5841:6379
        command: ["redis-server", "--appendonly", "yes"]
        networks:
        - redis-net
        volumes:
        - redis-data:/data

    postgres:
        image: postgres:latest
        restart: always
        ports:
          - 9627:5432
        environment:
            POSTGRES_PASSWORD: pg
            POSTGRES_USER: pg
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 3847:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres

volumes:
    redis-data:
    postgres:
    pgadmin:

networks:
    rabbitmq_net:
        driver: bridge
    redis-net: